=== lapin1/Appliances/appliances/target/classes/appliances.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/appliances"
        xmlns:tns="http://www.example.org/appliances">

    <element name = "appliance">
        <complexType>
            <sequence>
                <element name ="laptop" type="tns:Laptop" minOccurs="1" maxOccurs="unbounded"/>
                <element name ="oven" type="tns:Oven" minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Laptop">
        <sequence>
            <element name="battery-capacity" type="int" />
            <element name="price" type="string" />
            <element name="os" type="string" />
            <element name="memory-rom" type="int" />
            <element name="system-memory" type="int" />
            <element name="cpu" type="string" />
            <element name="display-inches" type="double" />
        </sequence>
        <attribute name="id" type="int" use="required" />
    </complexType>

    <complexType name="Oven">
        <sequence>
            <element name="price" type="double" />
            <element name="power-consumption" type="int" />
            <element name="weight" type="int" />
            <element name="capacity" type="int" />
            <element name="depth" type="double" />
            <element name="height" type="double" />
            <element name="width" type="double" />
        </sequence>
        <attribute name="id" type="int" use="required" />
    </complexType>
</schema>

=== lapin1/Appliances/appliances/target/classes/appliances.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:appliance xmlns:tc="http://www.example.org/appliances"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.example.org/appliance  appliances.xsd">

    <laptop id = "1">
        <battery-capacity>4800</battery-capacity>
        <price>3000</price>
        <os>macOS</os>
        <memory-rom>8</memory-rom>
        <system-memory>500</system-memory>
        <cpu>apple silicon</cpu>
        <display-inches>13.3</display-inches>
    </laptop>
    <laptop id = "2">
        <battery-capacity>4000</battery-capacity>
        <price>2000</price>
        <os>Windows</os>
        <memory-rom>4</memory-rom>
        <system-memory>1000</system-memory>
        <cpu>intel</cpu>
        <display-inches>15.6</display-inches>
    </laptop>
    <laptop id = "3">
        <battery-capacity>2500</battery-capacity>
        <price>1000</price>
        <os>Linux</os>
        <memory-rom>16</memory-rom>
        <system-memory>1000</system-memory>
        <cpu>intel</cpu>
        <display-inches>17.3</display-inches>
    </laptop>
    <oven id = "1">
        <price>1000</price>
        <power-consumption>1200</power-consumption>
        <weight>10</weight>
        <capacity>2300</capacity>
        <depth>60</depth>
        <height>40</height>
        <width>50</width>
    </oven>
    <oven id = "2">
        <price>1200</price>
        <power-consumption>1400</power-consumption>
        <weight>15</weight>
        <capacity>2600</capacity>
        <depth>70</depth>
        <height>50</height>
        <width>60</width>
    </oven>
    <oven id = "3">
        <price>1700</price>
        <power-consumption>1100</power-consumption>
        <weight>16</weight>
        <capacity>2700</capacity>
        <depth>65</depth>
        <height>50</height>
        <width>40</width>
    </oven>
</tc:appliance>
